#!/bin/sh

# Near-misses fail with SIGILL or SIGSEGV, we don't want core dumps.
ulimit -c 0

for x in $0-*
  do
    ARCH="$(basename "$x")"
    ARCH="${ARCH##arch-detect-}"
    MSG=`"$x" 2>/dev/null`
    if [ $? -eq 0 -a "x$MSG" = "xok" ]
      then echo "$ARCH"
    fi
  done
