.TH arch-detect 1
.SH NAME
arch-detect-* \- architecture detection helpers
.SH SYNOPSIS
.B arch-detect-$ARCH
.SH DESCRIPTION
These programs check whether the running kernel can execute binaries of a
given architecture.  When run, if successful, each such program prints
\&\fI"ok"\fR on stdout and returns exit code 0.
.SS Failure
When the check fails, these helper programs often die horribly.  Usually the
kernel will notice the incompatibility and nicely abort the attempt, but in some
near-miss cases the failure might be more messy, such as \fISIGILL\fR or
\&\fISIGSEGV\fR.  Thus, you do want to redirect \fIstderr\fR to
\&\fI/dev/null\fR and disable core dumps (\fBulimit \-c 0\fR).
.SH "SEE ALSO"
.B arch\-detect(1)
