.TH arch-detect 1
.SH NAME
arch-detect \- detect architectures your kernel can run
.SH SYNOPSIS
.B arch-detect
.SH DESCRIPTION
\&\fBarch-detect\fR outputs the list of architectures executable by your running
kernel, one per line, using Debian arch names.  \fILibc\fR or other libraries
are neither needed nor checked \(em an arch is listed if its machine code can
be executed and the appropriate syscall \s-1ABI\s0 is supported by the kernel.
This means, you can run these architectures in a \fIchroot\fR or a container,
execute them using multiarch, run static binaries, etc.  The ability to
run additional architectures can be gained via \fIbinfmt\fRs on Linux, Linux
emulation on BSD, etc.
.SS "Helper programs"
You can check the presence of a specific architecture directly by executing
\&\fB/usr/bin/arch\-detect\-$ARCH\fR, although you're advised to redirect the
\&\fIstderr\fR and disable core dumps (\fBulimit \-c 0\fR) as certain checks give a
negative answer rather messily.
.SH "SEE ALSO"
arch\-detect\-*
