#!/bin/bash

# Verbose script for debug purposes.

for x in arch-detect-*
  do
    arch=${x##arch-detect-}
    printf '\e[33m%s\e[0m\n' "$x"
    MSG=`"./$x" 2>/dev/null|tr -d '\r'`
    RET=$?
    if [ $RET -eq 0 -a "x$MSG" = "xok" ]
      then COL="32" # green
      else COL="31" # red
    fi
    printf '\e[%smret=\e[1m%d\e[0;%sm stdout=\e[1m%s\e[0m\n' "$COL" "$RET" "$COL" "$MSG"
  done
